openapi: 3.0.0
info:
  version: 1.0.0
  title: Efront Account Autologin API
  description: Efront API Documentation
servers:
- url: https://virtserver.swaggerhub.com/Epignosis/Efront-API/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://ssc.efrontlearning.com/API/v1.0
security:
- basicAuth: []
tags:
- name: Autologin
paths:
  /Autologin/{loginName}:
    get:
      tags:
      - Autologin
      description: Returns the auto-login URL for the requested user.
      parameters:
      - $ref: '#/components/parameters/loginName'
      responses:
        '200':
          description: A JSON array which contains the auto-login url for the requested user login name.
          content:
            application/json:
              schema:
                allOf:
                - type: object
                  properties:
                    data:
                      type: string
                      example: /start/op/autologin/login/{loginName}/autologin/5306553b00f3a3292f20dcbf5d26c2f0
                - $ref: '#/components/schemas/standardResponse'
        '400':
          $ref: '#/components/responses/errorResponse'
        '404':
          $ref: '#/components/responses/404NotFound'
components:
  responses:
    errorResponse:
      description: Bad request
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                error:
                  type: object
                  properties:
                    code:
                      type: integer
                      description: same as the response code
                      minimum: 400
                      default: 400
                    message:
                      type: string
                      description: A message that points out that something went wrong.
                      example: Not possible to get the requested resource information.
                    reason:
                      type: string
                      nullable: true
            - $ref: '#/components/schemas/standardResponse'
    404NotFound:
      description: Bad request
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                error:
                  type: object
                  properties:
                    code:
                      type: integer
                      description: same as the response code
                      default: 404
                    message:
                      type: string
                      description: A message that points out that something went wrong.
                      example: The requested resource was not found.
                    reason:
                      type: string
                      nullable: true
            - $ref: '#/components/schemas/standardResponse'
  parameters:
    loginName:
      name: loginName
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: username1
  schemas:
    standardResponse:
      type: object
      properties:
        executionDuration:
          type: number
          format: float
          example: 0.5281
        success:
          type: boolean
          enum:
          - true
          - false
        version:
          type: number
          format: float
          default: '1.0'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
