openapi: 3.2.0
info:
  version: 1.0.0
  title: Efront User Type API
  description: Efront API Documentation
servers:
- url: https://virtserver.swaggerhub.com/Epignosis/Efront-API/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://ssc.efrontlearning.com/API/v1.0
security:
- basicAuth: []
tags:
- name: User Type
paths:
  /user-types:
    get:
      tags:
      - User Type
      description: Returns the list of the available user types.
      responses:
        '200':
          description: A JSON array of user types.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      $ref: '#/components/schemas/id'
                    name:
                      type: string
                      example: Administrator
                    basic_user_type:
                      type:
                      - integer
                      - 'null'
                      minimum: 1
        '400':
          $ref: '#/components/responses/errorResponse'
      summary: Get user types
      x-summary-source: derived
      operationId: getUserTypes
      x-operation-id-source: derived
  /user-type/{id}:
    get:
      tags:
      - User Type
      description: Returns information about user type with the requested identifier.
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: A JSON array of the specific user type.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/id'
                  name:
                    type: string
                    example: Administrator
                  basic_user_type:
                    type:
                    - integer
                    - 'null'
                    minimum: 1
        '400':
          $ref: '#/components/responses/errorResponse'
      summary: Get user type by id
      x-summary-source: derived
      operationId: getUserTypeById
      x-operation-id-source: derived
components:
  schemas:
    standardResponse:
      type: object
      properties:
        executionDuration:
          type: number
          format: float
          example: 0.5281
        success:
          type: boolean
          enum:
          - true
          - false
        version:
          type: number
          format: float
          default: '1.0'
    id:
      type: integer
      format: int32
      minimum: 1
      description: The resource id.
  responses:
    errorResponse:
      description: Bad request
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                error:
                  type: object
                  properties:
                    code:
                      type: integer
                      description: same as the response code
                      minimum: 400
                      default: 400
                    message:
                      type: string
                      description: A message that points out that something went wrong.
                      example: Not possible to get the requested resource information.
                    reason:
                      type:
                      - string
                      - 'null'
            - $ref: '#/components/schemas/standardResponse'
  parameters:
    id:
      name: id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        minimum: 1
        type: integer
        format: int32
        example: 1
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
